version: "3.3"
services:
  web:
    environment:
      - ASPNETCORE_URLS=http://177.10.10.10:80
    build: ./BlazorFrontEnd
    networks:
      proj_net:
        ipv4_address: 177.10.10.10
    ports:
      - "80:80"
    depends_on:
      - api
    links:
      - api
  api:
    environment:
      - ASPNETCORE_URLS=http://177.10.10.11:81
    build: ./RestWebApi
    networks:
      proj_net:
        ipv4_address: 177.10.10.11
    ports:
      - "81:81"
  db:
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:2920
    build: ./DataBase
    networks:
      proj_net:
        ipv4_address: 177.10.10.12
    ports:
      - "2920:2920"
    

networks:
  proj_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 177.10.10.0/24