// <auto-generated />
using System;
using Database.Db.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataBase.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210309165658_initialcreate")]
    partial class initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("Model.Item", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("cost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<string>("imageName")
                        .HasColumnType("TEXT");

                    b.Property<string>("nameOfItem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("itemsDbSet");
                });

            modelBuilder.Entity("Model.Order", b =>
                {
                    b.Property<int>("orderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("boughtItemid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nameOfBuyer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("timeOfOrder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("orderId");

                    b.HasIndex("boughtItemid");

                    b.ToTable("ordersDbSet");
                });

            modelBuilder.Entity("Model.Order", b =>
                {
                    b.HasOne("Model.Item", "boughtItem")
                        .WithMany()
                        .HasForeignKey("boughtItemid");

                    b.Navigation("boughtItem");
                });
#pragma warning restore 612, 618
        }
    }
}
